# Generated by Django 3.2.3 on 2021-08-05 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.ImageField(null=True, upload_to='capacitacion')),
                ('titulo', models.CharField(max_length=250)),
                ('fecha', models.CharField(max_length=500)),
                ('hora', models.CharField(max_length=500)),
                ('enlace', models.URLField()),
                ('inversión', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.ImageField(null=True, upload_to='empleo')),
                ('puesto', models.CharField(max_length=100)),
                ('objetivos', models.CharField(max_length=350)),
                ('experiecia', models.CharField(max_length=350)),
                ('habilidades', models.CharField(max_length=400)),
                ('contactos', models.CharField(max_length=850)),
            ],
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.ImageField(null=True, upload_to='emprendimiento')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('propietario', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Graduado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cedula')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='perfil')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=250, verbose_name='Apellido')),
                ('direccion', models.CharField(blank=True, max_length=350, null=True, verbose_name='Dirección')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('f_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nacionalidad')),
                ('etnia', models.CharField(blank=True, choices=[('Mestizo', 'Mestizo'), ('Afroecuatoriano', 'Afroecuatoriano'), ('Indígena', 'Indígena'), ('Blanco', 'Blanco'), ('Montubio', 'Montubio'), ('Amazonico', 'Amazonico')], default='Mestizo', max_length=50, null=True, verbose_name='Etnia')),
                ('genero', models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=50, null=True, verbose_name='Género')),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Unión de Hechos', 'Unión de Hechos'), ('Divorciado/a', 'Divorciado/a'), ('Casado/a', 'Casado/a'), ('Viudo/a', 'Viudo/a')], default='Soltero/a', max_length=50, null=True, verbose_name='Estado Civil')),
                ('discapacidad', models.CharField(blank=True, max_length=70, null=True, verbose_name='Discapacidad')),
                ('carrera', models.CharField(blank=True, choices=[('Agroindustrias', 'Agroindustrias'), ('Contabilidad', 'Contabilidad'), ('Desarrollo Infantil', 'Desarrollo Infantil'), ('Procesamiento de Alimentos', 'Procesamiento de Alimentos'), ('Desarrollo de Software', 'Desarrollo de Software'), ('Mecánica Automotriz', 'Mecánica Automotriz'), ('Electricidad', 'Electricidad'), ('Seguridad Ciudadana y Orden Público', 'Seguridad Ciudadana y Orden Público')], default='Agroindustrias', max_length=50, null=True, verbose_name='Carrera')),
                ('f_ingreso', models.DateField(verbose_name='Fecha de ingreso a la carrera')),
                ('f_salida', models.DateField(verbose_name='Fecha de graduación')),
                ('titulacion', models.CharField(blank=True, choices=[('Tesis', 'Tesis'), ('Examen complexivo', 'Examen complexivo')], default='Tesis', max_length=20, null=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=250, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
