# Generated by Django 3.2.3 on 2021-08-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduado',
            name='f_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso a la carrera'),
        ),
        migrations.AlterField(
            model_name='graduado',
            name='f_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='graduado',
            name='f_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de graduación'),
        ),
    ]
