# Generated by Django 3.2.3 on 2021-08-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_graduado_celular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduado',
            options={'verbose_name': 'Graduado'},
        ),
    ]
