# Generated by Django 3.2.3 on 2021-08-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_graduado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduado',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
    ]
