# Generated by Django 3.2.3 on 2021-08-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_administrador_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduado',
            name='cedula',
            field=models.CharField(max_length=15, verbose_name='Cedula'),
        ),
    ]
