# Generated by Django 3.2.3 on 2021-08-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20210827_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduado',
            name='genero',
            field=models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=50, null=True, verbose_name='Género'),
        ),
    ]
