# Generated by Django 3.2.3 on 2021-08-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_graduado_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduado',
            name='cargo',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='graduado',
            name='zona',
            field=models.CharField(blank=True, choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], max_length=50, null=True),
        ),
    ]
