# Generated by Django 3.2.3 on 2021-08-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_auto_20210828_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduado',
            name='razon',
        ),
    ]
