# Generated by Django 3.2.3 on 2021-08-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_remove_graduado_razon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduado',
            name='cursos',
        ),
    ]
