# Generated by Django 3.2.3 on 2021-08-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_auto_20210828_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='capacitacion'),
        ),
        migrations.AlterField(
            model_name='empleo',
            name='portada',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='empleo'),
        ),
        migrations.AlterField(
            model_name='graduado',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='perfil'),
        ),
    ]
