# Generated by Django 3.2.3 on 2021-08-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_auto_20210828_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduado',
            name='n_cursos',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9'), ('10 o más', '10 o más')], max_length=20, null=True),
        ),
    ]
